package settings

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"testing"

	sqlitestore "github.com/Sanoy24/ytgrab/internal/store/sqlite"
)

const exportedCookies = "# Netscape HTTP Cookie File\n# This file is generated by a browser extension.\n\n" +
	".youtube.com\tTRUE\t/\tTRUE\t1893456000\tPREF\tf6=40000000\n" +
	"#HttpOnly_.youtube.com\tTRUE\t/\tTRUE\t1893456000\tSID\tabc\n"

func TestCookieFileImport(t *testing.T) {
	ctx := context.Background()
	store, err := sqlitestore.Open(ctx, filepath.Join(t.TempDir(), "jobs.db"))
	if err != nil {
		t.Fatal(err)
	}
	defer store.Close()
	manager, err := New(ctx, store, t.TempDir(), false)
	if err != nil {
		t.Fatal(err)
	}
	file := filepath.Join(t.TempDir(), "cookies.txt")
	manager.SetCookieFile(file)

	// Choosing the file before importing one is refused.
	if err := manager.SetCookiesBrowser(ctx, CookieFileSetting); !errors.Is(err, ErrNoCookieFile) {
		t.Fatalf("file before import = %v", err)
	}
	for name, bad := range map[string]string{
		"no header":    ".youtube.com\tTRUE\t/\tTRUE\t1893456000\tPREF\tx\n",
		"no cookies":   "# Netscape HTTP Cookie File\n# nothing here\n",
		"JSON export":  `[{"domain":".youtube.com","name":"SID","value":"abc"}]`,
		"wrong fields": "# Netscape HTTP Cookie File\n.youtube.com TRUE / TRUE 0 PREF x\n",
	} {
		if err := manager.ImportCookies(ctx, []byte(bad)); !errors.Is(err, ErrInvalidCookieFile) {
			t.Errorf("%s accepted: %v", name, err)
		}
	}
	if err := manager.ImportCookies(ctx, []byte(exportedCookies)); err != nil {
		t.Fatal(err)
	}
	if manager.CookiesBrowser() != CookieFileSetting || manager.CookiesSource() != file {
		t.Fatalf("after import: %q %q", manager.CookiesBrowser(), manager.CookiesSource())
	}
	// The choice survives a restart.
	reloaded, err := New(ctx, store, t.TempDir(), false)
	if err != nil {
		t.Fatal(err)
	}
	reloaded.SetCookieFile(file)
	if reloaded.CookiesSource() != file {
		t.Fatalf("reloaded source = %q", reloaded.CookiesSource())
	}
	// Switching to a browser deletes the file, leaving no sign-in data behind.
	if err := manager.SetCookiesBrowser(ctx, "firefox"); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(file); !os.IsNotExist(err) {
		t.Error("the cookies file was kept")
	}
	if manager.CookiesSource() != "firefox" {
		t.Errorf("source = %q", manager.CookiesSource())
	}
}

func TestYtdlpChannelPersists(t *testing.T) {
	ctx := context.Background()
	store, err := sqlitestore.Open(ctx, filepath.Join(t.TempDir(), "jobs.db"))
	if err != nil {
		t.Fatal(err)
	}
	defer store.Close()
	manager, err := New(ctx, store, t.TempDir(), false)
	if err != nil {
		t.Fatal(err)
	}
	if manager.YtdlpChannel() != "stable" {
		t.Fatalf("default = %q", manager.YtdlpChannel())
	}
	if err := manager.SetYtdlpChannel(ctx, "beta"); !errors.Is(err, ErrInvalidPreference) {
		t.Fatalf("unknown channel = %v", err)
	}
	if err := manager.SetYtdlpChannel(ctx, "nightly"); err != nil {
		t.Fatal(err)
	}
	reloaded, err := New(ctx, store, t.TempDir(), false)
	if err != nil || reloaded.YtdlpChannel() != "nightly" {
		t.Fatalf("reloaded = %q, %v", reloaded.YtdlpChannel(), err)
	}
	if manager.Snapshot().YtdlpChannel != "nightly" {
		t.Error("the channel isn't in backups")
	}
}
