#!/bin/sh
# Renders the Homebrew formula, Scoop manifest, and winget manifests for a published release.
#
#   scripts/render-packages.sh 1.5.0 out/
#
# Writes out/Formula/ytgrab.rb, out/bucket/ytgrab.json, and the winget manifests in
# out/manifests/s/Sanoy24/YTGrab/VERSION/, using the .sha256 files that the release
# workflow publishes next to each archive.
set -eu

version="${1:?usage: render-packages.sh VERSION OUTDIR}"
out="${2:?usage: render-packages.sh VERSION OUTDIR}"
version="${version#v}"
root="$(cd "$(dirname "$0")/.." && pwd)"
base="https://github.com/Sanoy24/ytgrab/releases/download/v$version"

checksum() {
    sum="$(curl -fsSL "$base/ytgrab-$version-$1.sha256" | cut -d ' ' -f 1)"
    if ! printf '%s' "$sum" | grep -Eq '^[0-9a-f]{64}$'; then
        echo "no valid checksum for $1 in release v$version" >&2
        exit 1
    fi
    printf '%s' "$sum"
}

darwin_arm64="$(checksum darwin-arm64.tar.gz)"
darwin_amd64="$(checksum darwin-amd64.tar.gz)"
linux_arm64="$(checksum linux-arm64.tar.gz)"
linux_amd64="$(checksum linux-amd64.tar.gz)"
windows_amd64="$(checksum windows-amd64.zip)"
windows_amd64_upper="$(printf '%s' "$windows_amd64" | tr 'a-f' 'A-F')"
release_date="$(date -u +%Y-%m-%d)"

render() {
    sed -e "s/{{VERSION}}/$version/g" \
        -e "s/{{SHA256_DARWIN_ARM64}}/$darwin_arm64/g" \
        -e "s/{{SHA256_DARWIN_AMD64}}/$darwin_amd64/g" \
        -e "s/{{SHA256_LINUX_ARM64}}/$linux_arm64/g" \
        -e "s/{{SHA256_LINUX_AMD64}}/$linux_amd64/g" \
        -e "s/{{SHA256_WINDOWS_AMD64}}/$windows_amd64/g" \
        -e "s/{{SHA256_WINDOWS_AMD64_UPPER}}/$windows_amd64_upper/g" \
        -e "s/{{DATE}}/$release_date/g" \
        -e '/^# Generated by /d' \
        "$1" >"$2"
}

mkdir -p "$out/Formula" "$out/bucket"
render "$root/packaging/homebrew/ytgrab.rb.tmpl" "$out/Formula/ytgrab.rb"
render "$root/packaging/scoop/ytgrab.json.tmpl" "$out/bucket/ytgrab.json"
winget="$out/manifests/s/Sanoy24/YTGrab/$version"
mkdir -p "$winget"
for manifest in Sanoy24.YTGrab Sanoy24.YTGrab.installer Sanoy24.YTGrab.locale.en-US; do
    render "$root/packaging/winget/$manifest.yaml.tmpl" "$winget/$manifest.yaml"
done
echo "Rendered the Homebrew formula, Scoop manifest, and winget manifests for $version in $out"
